const config = window.ILUMINO;
const el = (tag, text, cls) => {const node=document.createElement(tag);if(text)node.textContent=text;if(cls)node.className=cls;return node;};
// Ícones de interface em traço simples, sem biblioteca ou chamadas externas.
function serviceIcon(number){const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('class','line-icon');svg.setAttribute('aria-hidden','true');const shapes={ '01':[['rect',{x:3,y:4,width:18,height:13,rx:2}],['path',{d:'M8 21h8M12 17v4M3 8h18'}]],'02':[['path',{d:'m12 3 9 5-9 5-9-5 9-5ZM3 12l9 5 9-5M3 16l9 5 9-5'}]],'03':[['circle',{cx:12,cy:12,r:8}],['circle',{cx:12,cy:12,r:3}],['path',{d:'M12 1v3M12 20v3M1 12h3M20 12h3'}]]};for(const [tag,attrs] of shapes[number]){const shape=document.createElementNS(ns,tag);for(const [key,value] of Object.entries(attrs))shape.setAttribute(key,value);svg.append(shape);}return svg;}
config.services.forEach(s=>{const row=el('article',null,'service reveal');const marker=el('div',null,'service-marker');marker.append(serviceIcon(s.number),el('span',s.number,'service-number'));row.append(marker);const main=el('div');main.append(el('h3',s.name),el('p',s.description));const tags=el('div',null,'tags');s.tags.forEach(t=>tags.append(el('span',t)));main.append(tags);const detail=el('details');detail.append(el('summary','Conheça a proposta'),el('p',s.detail));main.append(detail);row.append(main);const cta=el('a','Quero conversar','service-cta');cta.href='#briefing';row.append(cta);document.querySelector('#services').append(row);});
config.steps.forEach((s,i)=>{const card=el('article',null,'step reveal');card.append(el('span','0'+(i+1),'step-number'),el('h3',s[0]),el('p',s[1]));document.querySelector('#steps').append(card);});
config.faqs.forEach(f=>{const d=el('details');d.append(el('summary',f[0]),el('p',f[1]));document.querySelector('#faqs').append(d);});
function options(target,values,name){values.forEach((v,i)=>{const data=Array.isArray(v)?v:[v];const label=el('label',null,'choice');const input=el('input');input.type='radio';input.name=name;input.value=data[0];input.required=true;const content=el('span');content.append(el('strong',data[0]));if(data[1])content.append(el('small',data[1]));label.append(input,content);document.querySelector(target).append(label);});}
options('#service-choices',config.serviceChoices,'service');options('#goal-choices',config.goals,'goal');options('#time-choices',config.timing,'time');
const form=document.querySelector('#brief-form');const action=document.querySelector('#brief-action');const whatsapp=/^\d{10,15}$/.test(config.whatsapp);if(whatsapp){action.textContent='Continuar no WhatsApp';document.querySelector('.delivery-note').textContent='Você poderá revisar a mensagem no WhatsApp antes de enviar.';}
function selections(){return Object.fromEntries(new FormData(form));}
function summary(){const s=selections();return `Olá, Ilumino Creative! Quero conversar sobre um projeto.\n\nPreciso de: ${s.service}\nMinha prioridade: ${s.goal}\nGostaria de começar: ${s.time}\n\nPodemos conversar sobre o melhor caminho?`;}
form.addEventListener('change',()=>{const s=selections();document.querySelector('#result-title').textContent=s.service||'Selecione suas necessidades';document.querySelector('#result-detail').textContent=[s.goal,s.time].filter(Boolean).join(' · ')||'Continue escolhendo sua prioridade e momento.';action.disabled=!(s.service&&s.goal&&s.time);document.querySelector('#feedback').textContent='';document.querySelector('#copy-fallback').hidden=true;});
form.addEventListener('submit',async event=>{event.preventDefault();if(!form.reportValidity())return;const message=summary();if(whatsapp){window.open(`https://wa.me/${config.whatsapp}?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');document.querySelector('#feedback').textContent='Mensagem preparada. Confirme o envio no WhatsApp.';return;}try{await navigator.clipboard.writeText(message);document.querySelector('#feedback').textContent='Briefing copiado! Guarde o resumo para nossa conversa.';}catch{document.querySelector('#copy-fallback').hidden=false;const field=document.querySelector('#summary-text');field.value=message;field.focus();field.select();document.querySelector('#feedback').textContent='Seu navegador não permitiu copiar automaticamente. O resumo está disponível abaixo.';}});
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('#navigation');toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open);});nav.addEventListener('click',e=>{if(e.target.closest('a')){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');}});
document.querySelector('#year').textContent=new Date().getFullYear();
const tabs=Array.from(document.querySelectorAll('[role=tab]'));
function chooseTab(tab){tabs.forEach(button=>{const selected=button===tab;button.setAttribute('aria-selected',String(selected));button.tabIndex=selected?0:-1;document.getElementById(button.getAttribute('aria-controls')).hidden=!selected;});}
tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>chooseTab(tab));tab.addEventListener('keydown',event=>{let next=index;if(event.key==='ArrowRight'||event.key==='ArrowDown')next=(index+1)%tabs.length;else if(event.key==='ArrowLeft'||event.key==='ArrowUp')next=(index-1+tabs.length)%tabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=tabs.length-1;else return;event.preventDefault();chooseTab(tabs[next]);tabs[next].focus();});});
const tabList=document.querySelector('[role=tablist]');const mobileTabs=matchMedia('(max-width:700px)');function tabOrientation(){tabList.setAttribute('aria-orientation',mobileTabs.matches?'horizontal':'vertical');}tabOrientation();mobileTabs.addEventListener('change',tabOrientation);
const motionButton=document.querySelector('.motion-toggle');const light=document.querySelector('.light-composition');const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)');let userPaused=false;
function syncMotion(){const paused=userPaused||reduceMotion.matches;document.documentElement.dataset.motion=paused?'paused':'running';motionButton.setAttribute('aria-pressed',String(paused));motionButton.textContent=reduceMotion.matches?'Movimento reduzido':paused?'Retomar animações':'Pausar animações';motionButton.disabled=reduceMotion.matches;light.classList.toggle('motion-rest',paused);}
syncMotion();motionButton.addEventListener('click',()=>{userPaused=!userPaused;syncMotion();});reduceMotion.addEventListener('change',syncMotion);
const hero=document.querySelector('.hero');let lightFrame=0;const finePointer=matchMedia('(hover:hover) and (pointer:fine)');
hero.addEventListener('pointermove',event=>{if(!finePointer.matches||reduceMotion.matches||userPaused||lightFrame)return;lightFrame=requestAnimationFrame(()=>{const rect=hero.getBoundingClientRect();light.style.setProperty('--light-x',`${((event.clientX-rect.left)/rect.width-.5)*22}px`);light.style.setProperty('--light-y',`${((event.clientY-rect.top)/rect.height-.5)*15}px`);lightFrame=0;});});hero.addEventListener('pointerleave',()=>{light.style.setProperty('--light-x','0px');light.style.setProperty('--light-y','0px');});
if('IntersectionObserver' in window){const sectionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){nav.querySelectorAll('a').forEach(link=>{if(link.hash==='#'+entry.target.id)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current');});}}),{rootMargin:'-15% 0px -60% 0px'});document.querySelectorAll('section[id]').forEach(section=>sectionObserver.observe(section));}
if('IntersectionObserver' in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(n=>{n.classList.add('will-reveal');observer.observe(n);});}

