(()=>{
const config = {...window.ILUMINO, whatsapp: window.ILUMINO_SITE.whatsapp.replace(/\D/g,'')};
const el = (tag, text, cls) => {const node=document.createElement(tag);if(text)node.textContent=text;if(cls)node.className=cls;return node;};
function options(target,values,name){values.forEach((v,i)=>{const data=Array.isArray(v)?v:[v];const label=el('label',null,'choice');const input=el('input');input.type='radio';input.name=name;input.value=data[0];input.required=true;const content=el('span');content.append(el('strong',data[0]));if(data[1])content.append(el('small',data[1]));label.append(input,content);document.querySelector(target).append(label);});}
options('#service-choices',config.serviceChoices,'service');options('#goal-choices',config.goals,'goal');options('#time-choices',config.timing,'time');
const form=document.querySelector('#brief-form');const action=document.querySelector('#brief-action');const whatsapp=/^\d{10,15}$/.test(config.whatsapp);if(whatsapp){action.textContent='Continuar no WhatsApp';document.querySelector('.delivery-note').textContent='Você poderá revisar a mensagem no WhatsApp antes de enviar.';}
function selections(){return Object.fromEntries(new FormData(form));}
function summary(){const s=selections();return `Olá, Ilumino Creative! Quero conversar sobre um projeto.\n\nPreciso de: ${s.service}\nMinha prioridade: ${s.goal}\nGostaria de começar: ${s.time}\n\nPodemos conversar sobre o melhor caminho?`;}
form.addEventListener('change',()=>{const s=selections();document.querySelector('#result-title').textContent=s.service||'Selecione suas necessidades';document.querySelector('#result-detail').textContent=[s.goal,s.time].filter(Boolean).join(' · ')||'Continue escolhendo sua prioridade e momento.';action.disabled=!(s.service&&s.goal&&s.time);document.querySelector('#feedback').textContent='';document.querySelector('#copy-fallback').hidden=true;});
form.addEventListener('submit',async event=>{event.preventDefault();if(!form.reportValidity())return;const message=summary();if(whatsapp){window.open(`https://wa.me/${config.whatsapp}?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');document.querySelector('#feedback').textContent='Mensagem preparada. Confirme o envio no WhatsApp.';return;}try{await navigator.clipboard.writeText(message);document.querySelector('#feedback').textContent='Briefing copiado! Guarde o resumo para nossa conversa.';}catch{document.querySelector('#copy-fallback').hidden=false;const field=document.querySelector('#summary-text');field.value=message;field.focus();field.select();document.querySelector('#feedback').textContent='Seu navegador não permitiu copiar automaticamente. O resumo está disponível abaixo.';}});
})();
