const config=window.ILUMINO_SITE;
const ns='http://www.w3.org/2000/svg';const paths={target:'M12 3a9 9 0 1 0 9 9M12 7a5 5 0 1 0 5 5M12 12l9-9M17 3h4v4',layers:'m12 2 10 5-10 5L2 7l10-5ZM2 12l10 5 10-5M2 17l10 5 10-5',chart:'M3 21V13h4v8M10 21V8h4v13M17 21V3h4v18',pen:'m4 16-1 5 5-1L21 7l-5-5L4 16ZM14 4l5 5M4 16l4 4',tech:'M3 4h18v13H3V4ZM8 21h8M12 17v4',analysis:'M12 2v10h10A10 10 0 1 1 12 2ZM16 2v6h6a8 8 0 0 0-6-6'};
function icon(type){const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');const path=document.createElementNS(ns,'path');path.setAttribute('d',paths[type]||paths.target);svg.append(path);return svg;}
document.querySelectorAll('[data-icon]').forEach(el=>el.append(icon(el.dataset.icon)));
const brandTrack=document.querySelector('#brand-track');const group=document.createElement('div');group.className='brand-group';config.partners.forEach(partner=>{const item=document.createElement('div');item.className='brand-item partner-'+partner.style;const visual=document.createElement('span');visual.className='partner-logo';visual.setAttribute('role','img');visual.setAttribute('aria-label',partner.name);visual.style.backgroundImage='url("'+partner.logo+'")';item.append(visual);group.append(item);});brandTrack.append(group);const clone=group.cloneNode(true);clone.setAttribute('aria-hidden','true');clone.inert=true;brandTrack.append(clone);
const steps=[['Diagnostic','Diagnóstico','Entendemos seu cenário e objetivos.'],['Direction','Direção','Alinhamos a estratégia e o planejamento.'],['Production','Produção','Transformamos a ideia em uma solução.'],['Approval','Aprovação','Revisamos e validamos juntos.'],['Delivery','Entrega','Preparamos o lançamento e a entrega.'],['Evolution','Evolução','Definimos os próximos passos.']];steps.forEach((step,i)=>{const item=document.createElement('article');item.innerHTML='<span class="step-dot"></span><span class="step-number">0'+(i+1)+'</span>';const h=document.createElement('h3');h.textContent=step[1];const p=document.createElement('p');p.textContent=step[2];item.append(h,p);document.querySelector('#timeline').append(item);});
const fronts=[['target','Estratégia','Posicionamento e planejamento.'],['pen','Criação','Identidade visual, conteúdo e experiências.'],['chart','Conversão','Sites e páginas com foco no próximo passo.'],['tech','Tecnologia','Soluções digitais para seu negócio.'],['analysis','Análises','Aprendizados para orientar a comunicação.']];fronts.forEach(([type,title,copy])=>{const item=document.createElement('article');item.append(icon(type));const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=copy;item.append(h,p);document.querySelector('#front-grid').append(item);});
const faqs=[['Qual é o prazo de um projeto?','O cronograma é definido na proposta, de acordo com o escopo e as etapas de revisão.'],['Como funciona o processo de criação?','Começamos pela conversa e pelo diagnóstico. Depois alinhamos a direção, criamos, revisamos e entregamos.'],['Quais tipos de projeto vocês desenvolvem?','Sites, identidade visual e marketing, em uma frente específica ou em um projeto integrado.'],['Como é feito o orçamento?','Entendemos sua necessidade e apresentamos escopo, investimento e cronograma.'],['Preciso contratar tudo junto?','Não. Podemos começar pelo que faz mais sentido para sua fase.'],['Como funciona o suporte após a entrega?','As condições de suporte e continuidade são combinadas na proposta.']];faqs.forEach(([q,a])=>{const d=document.createElement('details');const s=document.createElement('summary');s.textContent=q;const p=document.createElement('p');p.textContent=a;d.append(s,p);document.querySelector('#faq-grid').append(d);});
const nav=document.querySelector('#navigation'),menu=document.querySelector('.menu');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open);});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');}});
const number=config.whatsapp.replace(/\D/g,'');document.querySelectorAll('.contact-link').forEach(a=>a.href=number?'https://wa.me/'+number+'?text='+encodeURIComponent('Olá, Ilumino! Gostaria de conversar sobre um projeto.'):'#briefing');if(config.logo){document.querySelectorAll('.brand').forEach(el=>{const img=document.createElement('img');img.src=config.logo;img.alt='Ilumino Creative';const symbol=el.querySelector('.logo-mark');if(symbol){symbol.textContent='';symbol.classList.add('official-symbol');symbol.style.backgroundImage='url("'+config.logo+'")';}else{el.replaceChildren(img);}});}document.querySelector('#year').textContent=new Date().getFullYear();const motion=document.querySelector('#motion-toggle'),reduced=matchMedia('(prefers-reduced-motion: reduce)');let paused=false;function sync(){const stop=paused||reduced.matches;document.documentElement.dataset.motion=stop?'paused':'running';motion.setAttribute('aria-pressed',String(stop));motion.textContent=reduced.matches?'Movimento reduzido':stop?'Retomar animações':'Pausar animações';motion.disabled=reduced.matches;}motion.addEventListener('click',()=>{paused=!paused;sync();});reduced.addEventListener('change',sync);sync();

// Revela cada bloco uma vez; animações contínuas só no processo visível.
if('IntersectionObserver' in window){
 const revealObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target);}});},{threshold:.08});
 document.querySelectorAll('.promise-copy,.promise-points article,.row-title,.timeline article,.front-grid article,#brief-form,.faq-grid details,.closing>div').forEach(el=>{el.classList.add('section-reveal');el.style.setProperty('--reveal-delay',Math.min([...el.parentElement.children].indexOf(el)*65,260)+'ms');revealObserver.observe(el);});
 const timeline=document.querySelector('#timeline');timeline.querySelectorAll('article').forEach((el,i)=>el.querySelector('.step-dot').style.setProperty('--pulse-delay',i*.45+'s'));
 new IntersectionObserver(entries=>entries.forEach(entry=>entry.target.classList.toggle('is-active',entry.isIntersecting)),{threshold:.15}).observe(timeline);
}
